config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('vehiculo/', include('vehiculo.urls')),
    path('usuarios/', include('usuarios.urls')),
    
]

config/usuarios/urls.py
from django.urls import path, include
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registro/', views.registrar_usuario, name='registrar_usuario'),
]

config/vehiculo/urls.py
from django.urls import path, include
from . import views

app_name = 'vehiculo'

urlpatterns = [
    path('add/', views.agregar_vehiculo, name='agregar_vehiculo'),
    path('list/', views.listar_vehiculos, name='listar_vehiculos'),
]

config/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Usuario(AbstractUser):
     def __str__(self):
        return self.username

config/vehiculo/models.py
from django.db import models

# Create your models here.
class Vehiculo(models.Model):
    MARCA_CHOICE =[
        ('fiat', 'Fiat'),
        ('chevrolet', 'Chevrolet'),
        ('ford', 'Ford'),
        ('toyota', 'Toyota'),   
    ]

    CATEGORIA_CHOICE=[
        ('particular', 'Particular'),
        ('transporte', 'Transporte'),
        ('carga', 'Carga'),
    ]

    #Creando modelo de vehiculo
    marca = models.CharField(max_length=20, choices=MARCA_CHOICE, default='ford')
    modelo = models.CharField(max_length=100)
    serial_carroceria = models.CharField(max_length=50)
    serial_motor = models.CharField(max_length=50)
    categoria = models.CharField(max_length=20, choices=CATEGORIA_CHOICE, default='particular')
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)

    class Meta:
        permissions = [
            ("visualizar_catalogo", "Puede ver el catalogo de vehiculos"),
        ]

    def __str__(self):
        return f" Marca: {self.marca} --- Modelo: {self.modelo}"
    
    @property
    def condicion_precio(self):
        if self.precio <= 10000:
            return "Bajo"
        elif 10000 < self.precio <= 30000:
            return "Medio"
        else:
            return "Alto"

config/usuarios/forms.py
from django import forms
from .models import Usuario

class RegistroUsuarioForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(widget=forms.PasswordInput, required=True)

    class Meta:
        model = Usuario
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")


        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return password2

    def save(self, commit=True):
        # Guardar el usuario, creando un usuario con la contraseña correctamente cifrada
        usuario = super().save(commit=False)
        password = self.cleaned_data["password1"]
        usuario.set_password(password)

        if commit:
            usuario.save()
        return usuario

    

    

config/vehiculo/forms.py
from django import forms
from .models import Vehiculo

class VehiculoForm(forms.ModelForm):
    
    class Meta:
        model = Vehiculo
        fields = '__all__'

config/config/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

config/usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from .forms import RegistroUsuarioForm
from django.contrib.auth.models import Permission
from vehiculo.models import Vehiculo
from django.contrib.contenttypes.models import ContentType


# Create your views here.
def login_view(request):
    if request.method =='POST':
        form = AuthenticationForm(request, data= request.POST )
        if form.is_valid():
            login(request, form.get_user())
            messages.success(request, 'Se ha iniciado sesión con éxito')
            return redirect('index')
    
    else:
        form =  AuthenticationForm()

    return render(request,'usuarios/login.html', {'form': form})

def logout_view(request):
    logout(request)
    messages.success(request, 'Sesión cerrada con éxito')
    return redirect('usuarios:login')



@login_required
def registrar_usuario(request):
    if request.method == 'POST':
        form = RegistroUsuarioForm(request.POST)
        if form.is_valid():
            usuario = form.save()  # Guardar el usuario

            # Asignar permiso y crear contexto
            content_type = ContentType.objects.get_for_model(Vehiculo)
            permiso = Permission.objects.get(codename='visualizar_catalogo', content_type=content_type)
            usuario.user_permissions.add(permiso)

            context = {'form': form, 'user': usuario}  # Añadir 'user' al contexto
            return render(request, 'usuarios/registro.html', context)
    else:
        form = RegistroUsuarioForm()

    return render(request, 'usuarios/registro.html', {'form': form})
            

config/vehiculo/views.py
from django.shortcuts import render, redirect
from .forms import VehiculoForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from .models import Vehiculo

# Create your views here.

@login_required
@permission_required('vehiculo.visualizar_catalogo', raise_exception=True)
def listar_vehiculos(request):
    vehiculos = Vehiculo.objects.all()
    return render(request, 'vehiculo/listar_vehiculo.html', {'vehiculos': vehiculos})


@login_required
@permission_required('vehiculo.add_vehiculo', raise_exception=True)
def agregar_vehiculo(request):
    if request.method =='POST':
        form = VehiculoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = VehiculoForm()
    return render(request, 'vehiculo/agregar_vehiculo.html', {'form':form})
    

config/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %}Pagina Principal{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand text-white" href="{% url 'index' %}">Vehiculos</a>
            <ul class="navbar-nav">
                <li class="navbar-item"> <a class="nav-link text-white"  href="{% url 'index' %}">Inicio</a></li>
                {% if request.user.is_superuser %}
                    <li class="navbar-item"> <a class="nav-link text-white" href="{% url 'usuarios:registrar_usuario' %}">Registrar usuario</a></li>
                    {% endif %}
                {% if user.is_staff %}
                    <li class="navbar-item"><a class="nav-link text-white" href="{% url 'vehiculo:agregar_vehiculo' %}">Agregar</a></li>
                {% endif %}

                {% if user.is_authenticated %}  
                    <li class="navbar-item"> <a class="nav-link text-white" href="{% url 'vehiculo:listar_vehiculos' %}">Listar</a></li>
                {% endif %}
            </ul>

            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'usuarios:logout' %}">Cerrar sesión</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Hola, {{user.username}}</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'usuarios:login' %}">Iniciar sesión</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
        
</body>
</html>

config/templates/index.html
{% extends 'base.html' %}
{%block title%}Pagina Principal{%endblock%}

{%block content%}

<h1>Catalogo de Vehiculos</h1>


{%endblock%}

config/usuarios/templates/usuarios/login.html
{% extends "base.html" %}
{%block title%}Inicio de Sesion{% endblock %}

{%block content%}

<h2>Iniciar Sesión</h2>
<form class="p-3" method = "post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary m-2">Iniciar Sesión</button>
</form>
</div>

{%endblock%}

config/usuarios/templates/usuarios/registro.html
{% extends "base.html" %}
{%block title%}Registro{% endblock %}

{%block content%}

<h2>Registro de usuario</h2>
<form class="p-3" method = "post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary m-2">Crear usuario</button>
</form>
</div>

{%endblock%}

config/vehiculo/templates/vehiculo/agregar_vehiculo.html
{% extends "base.html" %}
{%block title%}Agregar Vechiculo{%endblock%}

{%block content%}

<div class="formulario">
    <form class="p-3" method = "post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary m-2">Agregar</button>
    </form>

    <a class="btn btn-danger m-2" href="{% url 'index' %}">Cancelar</a>
</div>

{%endblock%}

config/vehiculo/templates/vehiculo/listar_vehiculo.html
{% extends 'base.html' %}
{% block content %}
<h2>Listado de Vehículos</h2>

<div class="container-fluid">
    <table class="table table-striped table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Serial Carroceria</th>
                <th>Serial Motor</th>
                <th>Categoría</th>
                <th>Precio</th>
                <th>Condición de Precio</th>
            </tr>
        </thead>
        <tbody>
            {% for vehiculo in vehiculos %}
            <tr>
                <td>{{ vehiculo.marca }}</td>
                <td>{{ vehiculo.modelo }}</td>
                <td>{{ vehiculo.serial_carroceria }}</td>
                <td>{{ vehiculo.serial_motor }}</td>
                <td>{{ vehiculo.categoria }}</td>
                <td>{{ vehiculo.precio }}</td>
                <td>{{ vehiculo.condicion_precio }}</td>
                
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">
                    <h5>No hay vehiculos registrados</h5>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



{% endblock %}


<div class="container">
    <table>
        <thead>
            <tr>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Serial Carroceria</th>
                <th>Serial Motor</th>
                <th>Categoría</th>
                <th>Precio</th>
                <th>Condición de Precio</th>

            </tr>
        </thead>
        <tbody>
            {% for vehiculo in vehiculos %}
            <tr>
                <td>{{ vehiculos.marca }}</td>
                <td>{{ vehiculos.modelo }}</td>
                <td>{{ vehiculos.serial_carroceria }}</td>
                <td>{{ vehiculos.serial_motor }}</td>
                <td>{{ vehiculos.categoria }}</td>
                <td>{{ vehiculos.precio }}</td>
                <td>{{ vehiculos.condicion_precio }}</td>
                
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">
                    <h5>No hay productos disponibles</h5>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>